#!/usr/bin/env bash

#autostart
wlr-randr --output eDP-1 --on --mode 2880x1800@60.000999 --scale 1.75 &
dbus-launch waybar &
fcitx5 &
dunst &
swaybg -i /etc/nixos/profiles/laptop/resources/wallpaper.jpg &

#modkey
mod="Mod4"

#bindings
riverctl map normal $mod T spawn "fuzzel --prompt='  ' --terminal='kitty -e' --background=0b151dff --text=c6d2edff --selection-color=ac8aacff --selection-text=0b151dff --border-width=2 --border-color=404b66ff --icon-theme=Papirus-Dark --match-color=bd6b6aff --font='mononoki Nerd Font':size=12 --lines=10 --line-height=20"
riverctl map normal $mod+Shift N spawn "playerctl play-pause"
riverctl map normal $mod+Shift M spawn "playerctl next"
riverctl map normal $mod L spawn kitty
riverctl map normal $mod B spawn firefox
riverctl map normal $mod O spawn "hyprpicker -a"
riverctl map normal $mod C spawn "wlr-randr --output eDP-1 --on --mode 2880x1800@60.000999 --scale 1.00 && sleep 1 && dbus-launch flameshot gui && sleep 1 && wlr-randr --output eDP-1 --on --mode 2880x1800@60.000999 --scale 1.75"
riverctl map normal $mod Z close
riverctl map normal $mod+Shift X exit
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl map normal $mod A resize horizontal -100
riverctl map normal $mod S resize vertical 100
riverctl map normal $mod D resize vertical -100
riverctl map normal $mod F resize horizontal 100
riverctl map normal $mod S focus-view next
riverctl map normal $mod D focus-view previous
riverctl map normal $mod+Shift S swap next
riverctl map normal $mod+Shift D swap previous
riverctl map normal $mod+Shift F toggle-fullscreen
riverctl map normal $mod X toggle-float
riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

#visual
riverctl border-color-focused 0xa6729f #0xac8aac #0x404B66
riverctl border-color-unfocused 0x404b66 #0x0B151D
riverctl border-width 1
riverctl default-layout rivertile
riverctl spawn "rivertile -main-ratio 0.50"

#windowrules
riverctl rule-add -app-id 'float*' -title 'ripdrag' float

#workspaces
for i in $(seq 1 6)
do
	tags=$((1 << ($i - 1)))
  riverctl map normal $mod $i set-focused-tags $tags
  riverctl map normal $mod+Shift $i set-view-tags $tags
  riverctl map normal $mod+Control $i toggle-focused-tags $tags
  riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

#misc
riverctl keyboard-layout us
riverctl input pointer-10248-536-ASUF1208:00_2808:0218_Touchpad tap enabled
riverctl input pointer-10248-536-ASUF1208:00_2808:0218_Touchpad drag enabled
riverctl input pointer-10248-536-ASUF1208:00_2808:0218_Touchpad disable-while-typing enabled enabled
riverctl input pointer-10248-536-ASUF1208:00_2808:0218_Touchpad middle-emulation enabled
riverctl input pointer-10248-536-ASUF1208:00_2808:0218_Touchpad natural-scroll enabled
riverctl input pointer-10248-536-ASUF1208:00_2808:0218_Touchpad tap-button-map left-right-middle
riverctl input pointer-10248-536-ASUF1208:00_2808:0218_Touchpad scroll method two-finger
riverctl focus-follows-cursor always
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
riverctl set-repeat 50 300
